-- Tabla propia del microservicio de Materiales.
CREATE TABLE materials (
  -- Oracle genera el identificador numérico.
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Referencia lógica al ID de MongoDB; no es una llave foránea entre bases.
  company_id    VARCHAR2(64) NOT NULL,
  material_type VARCHAR2(120) NOT NULL,
  -- La restricción protege la regla incluso si otro cliente omite la API.
  quantity      NUMBER(18, 3) NOT NULL CHECK (quantity > 0),
  unit          VARCHAR2(30) NOT NULL,
  location      VARCHAR2(160) NOT NULL,
  status        VARCHAR2(30) DEFAULT 'available' NOT NULL,
  -- UID de Firebase recibido de forma confiable desde el gateway.
  published_by  VARCHAR2(128) NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- Índices para búsquedas futuras por empresa y estado.
CREATE INDEX ix_materials_company ON materials (company_id);
CREATE INDEX ix_materials_status ON materials (status);
